# Site settings
title: Zibai Chen
description: My Resume Website
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zibai Chen
user_description: 
I am a consultant in the Enterprise Strategy practice at IBM. My experience spans both technology and strategy for startups to multinational corporations. Prior to joining IBM, I received my Bachelor of Science degree at the University of Toronto, with concentrations in Statistics and Mathematics.

user_title: Strategy Consultant 
email: zibai.c@outlook.com
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: zibai-chen
github_username: zibaic
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']

theme: jekyll-theme-cayman
